Revert "Update module github.com/minio/minio-go/v7 to v7.0.86 (forgejo) (#6945)"
This reverts commit 486acb04fa3bab041fc29e251f4381760028f2a3.

Because of https://github.com/minio/crc64nvme/pull/1
The package builds fail

https://codeberg.org/forgejo-integration/forgejo/actions/runs/7790#jobstep-10-2350

74.77 /go/pkg/mod/github.com/minio/crc64nvme@v1.0.0/crc64.go:128:9: undefined: updateAsm